In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## Creating arrays using list

In [3]:
myList = [1,2,3,4,5,6]
np.array(myList)

array([1, 2, 3, 4, 5, 6])

In [4]:
myNestedList = [[1,2,3], [2,3,4],[4,5,6]]
np.array(myNestedList)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [5]:
myList1 = [2,3,4]
myList2 = [3,4,5]
np.array([myList1, myList2])

array([[2, 3, 4],
       [3, 4, 5]])

## Creating arrays using functions

In [8]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(4,50,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5, dtype= int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(6, dtype= int)

array([1, 1, 1, 1, 1, 1])

In [15]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [16]:
np.full((5,5), 20, dtype =float)

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [80]:
np.info(np.full)

 full(shape, fill_value, dtype=None, order='C')

Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.

Examples
--------
>>> np.full((2, 2), np.inf)
array([[inf, inf],
       [inf, inf]])
>>> np.full((2, 2), 10)
array([[10,

In [20]:
x = np.array([1,0,4,4])
np.all(x)

True

In [22]:
np.any(x)

True

In [25]:
a = np.array([0,2,3,np.nan, np.inf])
a

array([ 0.,  2.,  3., nan, inf])

In [24]:
np.isinf(a)

array([False, False, False, False,  True])

In [26]:
np.isnan(a)

array([False, False, False,  True, False])

In [28]:
c = np.array([1+3j, 4, 3+7j, 8,9])
c

array([1.+3.j, 4.+0.j, 3.+7.j, 8.+0.j, 9.+0.j])

In [29]:
np.iscomplex(c)

array([ True, False,  True, False, False])

In [30]:
np.isreal(c)

array([False,  True, False,  True,  True])

## Comparison of arrays

In [31]:
x = np.array([1,2,3,4])
y = np.array([2,1,3,5])

In [32]:
np.greater(x,y)

array([False,  True, False, False])

In [33]:
np.less(x,y)

array([ True, False, False,  True])

In [34]:
np.greater_equal(x,y)

array([False,  True,  True, False])

In [35]:
np.less_equal(x,y)

array([ True, False,  True,  True])

In [39]:
v = np.identity(5, dtype= int)

v.shape

(5, 5)

In [41]:
np.random.normal(0,1)

0.06024838016981627

In [46]:
A = np.arange(10,22).reshape(6,2)
A

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [50]:
v = np.linspace(10,49,5, dtype = int)
v

array([10, 19, 29, 39, 49])

In [51]:
np.random.randint(0,11,6)

array([6, 4, 7, 1, 2, 9])

## Calculations

In [52]:
x = np.array([2,3,4,5])
y = np.array([3,5,6,7])
multiply = x*y

In [53]:
multiply

array([ 6, 15, 24, 35])

In [54]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [56]:
x = np.arange(20,32).reshape(4,3)
print(x)
np.sum(x)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


306

In [58]:
np.sum(x , axis=0) # columns 

array([ 98, 102, 106])

In [59]:
np.sum(x , axis= 1) # rows

array([63, 72, 81, 90])

In [62]:
x = np.array([1,2])
y = np.array([3,4])
np.dot(x,y)

11

In [63]:
np.multiply(x,y)

array([3, 8])

In [64]:
np.outer(x,y)

array([[3, 4],
       [6, 8]])

In [66]:
np.zeros_like(x)

array([0, 0])

In [67]:
np.arange(10,55).reshape(3,5,3)

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [68]:
np.__version__

'1.19.2'

## Broadcasting

In [69]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
newArr[:] = 10

In [71]:
newArr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [74]:
newArr[2:4] = 200

In [75]:
newArr

array([100, 100, 200, 200,  10,  10,  10,  10,  10,  10])

## Copy

In [76]:
copy = newArr.copy()

In [77]:
copy

array([100, 100, 200, 200,  10,  10,  10,  10,  10,  10])

In [78]:
copy[:5] = 15

In [79]:
copy

array([15, 15, 15, 15, 15, 10, 10, 10, 10, 10])